package com.example.dell.c1ean.DAO;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.dell.c1ean.Bean.WokerInaccount;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WOKER_INACCOUNT".
*/
public class WokerInaccountDao extends AbstractDao<WokerInaccount, Long> {

    public static final String TABLENAME = "WOKER_INACCOUNT";

    /**
     * Properties of entity WokerInaccount.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Worker_id = new Property(1, Long.class, "worker_id", false, "WORKER_ID");
        public final static Property Time = new Property(2, String.class, "time", false, "TIME");
        public final static Property Money = new Property(3, float.class, "money", false, "MONEY");
        public final static Property Payer = new Property(4, String.class, "Payer", false, "PAYER");
    }


    public WokerInaccountDao(DaoConfig config) {
        super(config);
    }
    
    public WokerInaccountDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WOKER_INACCOUNT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"WORKER_ID\" INTEGER," + // 1: worker_id
                "\"TIME\" TEXT NOT NULL ," + // 2: time
                "\"MONEY\" REAL NOT NULL ," + // 3: money
                "\"PAYER\" TEXT NOT NULL );"); // 4: Payer
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WOKER_INACCOUNT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, WokerInaccount entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long worker_id = entity.getWorker_id();
        if (worker_id != null) {
            stmt.bindLong(2, worker_id);
        }
        stmt.bindString(3, entity.getTime());
        stmt.bindDouble(4, entity.getMoney());
        stmt.bindString(5, entity.getPayer());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, WokerInaccount entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long worker_id = entity.getWorker_id();
        if (worker_id != null) {
            stmt.bindLong(2, worker_id);
        }
        stmt.bindString(3, entity.getTime());
        stmt.bindDouble(4, entity.getMoney());
        stmt.bindString(5, entity.getPayer());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public WokerInaccount readEntity(Cursor cursor, int offset) {
        WokerInaccount entity = new WokerInaccount( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // worker_id
            cursor.getString(offset + 2), // time
            cursor.getFloat(offset + 3), // money
            cursor.getString(offset + 4) // Payer
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, WokerInaccount entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setWorker_id(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setTime(cursor.getString(offset + 2));
        entity.setMoney(cursor.getFloat(offset + 3));
        entity.setPayer(cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(WokerInaccount entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(WokerInaccount entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(WokerInaccount entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
